name: Build and run tests on each code change
on: [ push, pull_request ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run code format check
        run: ./gradlew ktlintCheck

      - name: Run static analysis
        run: ./gradlew detekt

      - name: Build the application
        run: ./gradlew build -x check

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew integrationTest
